version: 2.1
orbs:
  jq: circleci/jq@1.9.0
aliases:
  set_git_credentials: &set_git_credentials
    run: |
        git config credential.helper 'cache --timeout=120'
        git config user.email ngChile@circleci
        git config user.name "ngChile Circle Ci Deployment Bot"
  install_lerna_globally: &install_lerna_globally
    run: 
      name: Install Lerna CLI and node modules
      command: |
        sudo npm install -g npm@latest && sudo npm install -g lerna@latest && sudo lerna exec 'npm ci'
  show_current_branch: &show_current_branch
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
jobs:
  unit-tests:
    docker:
      - image: circleci/node:10
    working_directory: ~/lib
    steps:
      - checkout
      - <<: *show_current_branch
      - <<: *install_lerna_globally
      - run:
          name: Running unit tests
          command: sudo lerna exec 'npm run test:ci -- --colors'
  e2e:
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm
    working_directory: ~/lib
    steps:
      - checkout
      - <<: *show_current_branch
      - run:
          name: Install jq #Using a non CircleCI's docker image the ORB for jq does not works
          command: |
            apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -yq install jq
      - run:
          name: Install Angular CLI and Lerna (without sudo in Cypress image)
          command: |
            npm install -g npm@latest && npm install -g @angular/cli@latest lerna@latest && lerna exec 'npm ci'
      - run:
          name: Running e2e test running schematic on sandbox app
          command: lerna run e2e
  publish:
    docker:
      - image: circleci/node:10
    working_directory: ~/lib
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f8:10:aa:a7:83:34:01:06:0e:b9:ba:89:ee:58:23:b6"
      - checkout
      - <<: *set_git_credentials
      - <<: *show_current_branch
      # circleci/node:10 needs sudo for run global packages
      - <<: *install_lerna_globally
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$AUTH_TOKEN" > ~/lib/.npmrc
      - run:
          name: Building Package
          command: sudo lerna run build
      - run:
          name: Publish package
          command: sudo lerna publish from-package --yes --force-publish
  update-repository:
    docker:
      - image: circleci/node:10
    working_directory: ~/lib
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f8:10:aa:a7:83:34:01:06:0e:b9:ba:89:ee:58:23:b6"
      - checkout
      - <<: *set_git_credentials
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Updating repository
          command: ./.circleci/update-contributors
workflows:
  version: 2
  angular-chile-pipeline:
    jobs:
      - unit-tests
      - e2e
      - publish:
          requires:
            - unit-tests
            - e2e
          filters:
            branches:
              only:
                - master
      - update-repository:
          requires:
            - publish
          filters:
            branches:
              only:
                - master
